version: "3.4"
networks:
  monitoring:
services:
  grafana:
    image: grafana/grafana-oss:8.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost
    networks: [monitoring]
  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    networks: [monitoring]
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
volumes:
  prometheus-data:
