server:
  port: 8181

spring:
  application.name: prometheus-grafana
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:file:./target/hsqldb/${spring.application.name};ifexists=false;hsqldb.lock_file=false
    username: sa
    password:
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

management:
  endpoints:
    web:
      exposure:
        include: "*" # expose prometheus endpoint
        exclude: "env,beans"
